apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.deploy_name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deploy_name }}
  ports:
    - port: 8085
      targetPort: 8080
      nodePort: 30003
